# Generated by Django 3.1.4 on 2020-12-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tc',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
